### ISSUE TITLE
measurement plugin crashes app on startup

### ISSUE THREAD

**Issue by SweetVlad** [ICRC-BME/PySigView#21]
**Describe the bug**
- app wont start if in previous session measurement plugin was closed

**To Reproduce**
1. close measurement window in open pysigview session
2. close app
3. open app with userconfig set to load

`WARNING: Traceback (most recent call last):
  File "/Users/vladimir/Documents/GitHub/PySigView/pysigview/plugins/measurement.py", line 638, in conn_disconn_signals
    self.sd.input_recieved.disconnect(self.signal_widget.recieve_input)
TypeError: 'method' object is not connected
WARNING:vispy:Traceback (most recent call last):
  File "/Users/vladimir/Documents/GitHub/PySigView/pysigview/plugins/measurement.py", line 638, in conn_disconn_signals
    self.sd.input_recieved.disconnect(self.signal_widget.recieve_input)
TypeError: 'method' object is not connected`

**Expected behavior**

**Desktop (please complete the following information):**
 - macOS
 - PySigView Version [last]

**Comment by cimbi** [comment]
I cannot reproduce this. I don' really understand 3. point. What do you mean by userconfig set to load?
Also in issue description provide exact version please.

**Comment by SweetVlad** [comment]
update:
1. open app
2. close measurement window (click "x")
3. close app
4. open app 
5. see crash

This part of config setup in main.py
# Main configuration instance
try:
    CONF = UserConfig('pysigview', defaults=DEFAULTS, load=True,
                      version=CONF_VERSION, subfolder=SUBFOLDER, backup=True,
                      raw_mode=True)
except Exception:
    CONF = UserConfig('pysigview', defaults=DEFAULTS, load=False,
                      version=CONF_VERSION, subfolder=SUBFOLDER, backup=True,
                      raw_mode=True)


WARNING: Traceback (most recent call last):
  File "/Users/vladimir/Documents/GitHub/PySigView/pysigview/plugins/measurement.py", line 638, in conn_disconn_signals
    self.sd.input_recieved.disconnect(self.signal_widget.recieve_input)
TypeError: 'method' object is not connected
WARNING:vispy:Traceback (most recent call last):
  File "/Users/vladimir/Documents/GitHub/PySigView/pysigview/plugins/measurement.py", line 638, in conn_disconn_signals
    self.sd.input_recieved.disconnect(self.signal_widget.recieve_input)
TypeError: 'method' object is not connected

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)


version - 0.0.a9
macOS

**Comment by cimbi** [comment]
can you try removing your config file? it is possible that it was left there by some older version and nor adjusted properly. I still cannot reproduce this error
